### ISSUE TITLE
Module "ScheduledTasks" for command "Get-ScheduledTasks" is not loaded by default on latest Win 11 versions

### ISSUE THREAD

**Issue by PeterAbnerASI** [seagull/disable-scheduledWaking#10]
I ran your script and got the error that the command "Get-ScheduledTasks" could not be resolved. After a little search, I found that the module "ScheduledTasks" which it depends on is not loaded on my fresh Win 11 install (this month).

I'd recommend adding the `Import-Module ScheduledTasks` at the beginning of the script to include latest builds.

Thanks for your awesome work :)

**Comment by seagull** [comment]
Pushed build 17 which adds a check for this. Thanks for the heads-up.
