### ISSUE TITLE
Error creating key, network name not found

### ISSUE THREAD

**Issue by enzedonline** [seagull/disable-scheduledWaking#6]
Hi,

I was trying to run this today, signed in as admin on my laptop and running powershell as administrator. I get an error after getting to the commit changes stage:

```
Press any key to commit changes.
- Running file...

PsExec v2.34 - Execute processes remotely
Copyright (C) 2001-2021 Mark Russinovich
Sysinternals - www.sysinternals.com

Error creating key file on [[pc name]]:
The network name cannot be found.

- Process completed!
```

It doesn't seem to have made any changes to the Reboot task, I guess it trips up on the error before reaching that point.

I manually copied in the PSExec files into my System32 to make sure it wasn't something there, like an old version etc..

I couldn't find any reference to key files being generated in your script, I guess this is from PSExec?

PsExec v2.34
Win ver 10.0.19043.0

**Comment by seagull** [comment]
Hi, new version doesn't use PsExec. Please try it and let me know.
